version: '3'
services:
  notifications:
    image: ddyrcz/cms-evo:notifications-latest
    container_name: notifications
    environment:
      - ConnectionStrings__CarsDbConnectionString=Server=db;Database=CMS;User Id=sa; Password=password123!;
      - GOOGLE_APPLICATION_CREDENTIALS=/app/cms-evo-firebase-adminsdk.json
