version: '3'
services:
  db:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=password123!
    volumes:
      - sqlvolume:/var/opt/mssql
    container_name: db
volumes:
  sqlvolume:
