version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=password123!
    volumes:
      - sqlvolume:/var/opt/mssql
    ports:
      - 1433:1433
    container_name: db
volumes:
  sqlvolume:
