version: '3'
services:
  db:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    volumes:
      - sqlvolume:/var/opt/mssql
volumes:
  sqlvolume:
