version: '3'
services:
  db:    
    environment:
      - SA_PASSWORD=${CMS_EVO_MSSQL_SA_PASSWORD}
  api:    
    image: ddyrcz/cms-evo-backend:latest
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db  
    container_name: api
