version: '3'
services:
  db:    
    environment:
      - SA_PASSWORD=${CMS_EVO_MSSQL_SA_PASSWORD}
  api:    
    image: ddyrcz/cms-evo:api-latest
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db  
    container_name: api
    environment:
      - ConnectionStrings__CarsDbConnectionString=Server=db;Database=CMS;User Id=sa; Password=${CMS_EVO_MSSQL_SA_PASSWORD};