// <auto-generated />
using System;
using CMS.Cars.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMS.Cars.Infrastructure.Migrations
{
    [DbContext(typeof(CarsDbContext))]
    [Migration("20190303150259_rename-property")]
    partial class renameproperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CMS.Cars.Domain.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("AcExpiry")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LiftUdtExpiry")
                        .HasColumnType("date");

                    b.Property<string>("Name");

                    b.Property<DateTime>("OcExpiry")
                        .HasColumnType("date");

                    b.Property<string>("RegistrationNumber");

                    b.Property<DateTime?>("TachoLegalizationExpiry")
                        .HasColumnType("date");

                    b.Property<DateTime>("TermTechnicalResearch")
                        .HasColumnType("date");

                    b.Property<string>("VinNumber");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
